services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/db
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
#    restart: always
    ports:
      - "5432:5432"
    volumes:
        - /var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: thegoodcorner
