services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5432:5432 # local:container
    env_file: .env
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
