### Tags - getAll
GET http://localhost:5000/tags

### Tags - getOne
GET http://localhost:5000/tags/1

### Tags - getOne
DELETE http://localhost:5000/tags/1


### Tags - createOne
POST http://localhost:5000/tags
content-type: application/json

{
  "name": "Tag 1"
}

### Categories - createOne
POST http://localhost:5000/categories
content-type: application/json

{
  "name": "Seconde category"
}

### Categories - patchOne
PATCH  http://localhost:5000/categories/1
content-type: application/json

{
  "name": "Updated category"
}

### Categories - getAll
GET http://localhost:5000/categories
### Categories - getOne
GET http://localhost:5000/categories/1

### Ads - getAll (with filter)
GET http://localhost:5000/ads?categoryIn=1

### Categories - getOne
GET http://localhost:5000/categories/1/ads

### Ads - getAll
GET http://localhost:5000/ads

### Ads - getOne
GET http://localhost:5000/ads/1
### Ads - getAll (with filter)
GET http://localhost:5000/ads?search=bike
### Ads - getAll (with order)
GET http://localhost:5000/ads?orderByPrice=DESC


### Ads - createOne
POST http://localhost:5000/ads
content-Type: application/json

  {
    "title": "Bougie",
    "price": 8,
    "description": "Une bougie parfumée",
    "imgUrl": "/images/bougie.webp",
    "tags": [{ "id": 1 }],
    "category": { "id": 1 }
  }


### Ads - deleteOne

DELETE http://localhost:5000/ads/2

### Ads - patchOne
PATCH http://localhost:5000/ads/1
content-type: application/json

 {
    "title": "Dame-jeanne",
    "price": 75,
    "description": "Une dame-jeanne en verre",
    "imgUrl": "/images/dame-jeanne.webp",
    "tags": [{ "id": 1 }],
    "category": { "id": 1 }
  }